version: '3.3'

services:
  tommasi-agro:
    container_name: tommasi-agro
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    restart: unless-stopped
    # Add healthcheck to ensure the application is running
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3091"]
      interval: 10s
      timeout: 5s
      retries: 3
